name: Unit Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unittest:
    name: Unit Test (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-26.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: true

      - name: Test
        run: go test -timeout 60s ./...

      - name: Test purego
        run: go test -tags purego -timeout 60s ./...

      - name: Vet
        run: go vet ./...
